<?php
return array(
    'main/slide' => ['Main', 'SlideRequest'],
    '' => ['Main', 'index'],
    'about' => ['About', 'index'],
    'services' => ['Services', 'index'],
    'portfolio' => ['Portfolio', 'index'],
    'portfolio/getProjects' => ['Portfolio', 'getProjects'],
    'portfolio/projects/([0-9]{1,})/?' => ['Portfolio', 'singleProjects'],
    'check/projects' => ['Portfolio', 'checkProjects'],
    'comment' => ['Comment', 'index'],
    'create/commit' => ['Comment', 'postCommit'],
    'comment/get_comments' => ['Comment', 'get_comments'],
    'comments/checkComment' => ['Comment', 'checkComment'],
    'contacts' => ['Contact', 'index'],
    'admin' => ['Admin', 'index'],
    'admin/projects' => ['Admin', 'galery'],
    'admin/project/edit/([0-9]{1,})/?' => ['Admin', 'editGalery'],
    'admin/upload/images/([0-9]{1,})/?' => ['Admin', 'uploadImage'],
    'admin/projects/delete/images/([0-9]{1,})/?' => ['Admin', 'deliteImage'],
    'admin/new-project' => ['Admin', 'newProject'],
    'admin/add-new-project' => ['Admin', 'addProject'],
    'admin/project/delete/([0-9]{1,})/?' => ['Admin', 'deleteProject'],
    'admin/redact-main' => ['Admin', 'redactWhatWeDo'],
    'admin/edit_main_element' => ['Admin', 'edit_element'],
    'admin/redact-about' => ['About', 'pageRedactAbout'],
    'admin/about_header_fon' => ['About', 'uploadAboutFon'],
    'admin/edit_about' => ['About', 'editAbout'],
    'admin/save' => ['Admin', 'saveUser'],
    'admin/comments/([0-9]{1,})/?' => ['Pagination', 'indexComment'],
    'admin/comments/publish/([0-9]{1,})/?' => ['Admin', 'publishComments'],
    'admin/comments/delete/([0-9]{1,})/?' => ['Admin', 'deleteComment'],
    'admin/redact-service' => ['Admin', 'editServices'],
    'admin/save_services' => ['Admin', 'save_services'],
    'admin/redact-price' => ['Admin', 'redact_price'],
    'admin/logout' => ['Admin', 'logout'],
    'login' => ['Admin', 'login'],
    'send_mail' => ['Mail', 'sendMail']
);


